#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := softAP-config

EXTRA_COMPONENT_DIRS += \
    $(abspath ../../../components/esp-idf)
    
include $(IDF_PATH)/make/project.mk